In [ ]:
# Some library i have imported for matrix calculation and 
# tablabur representation
import numpy as np
import pandas as pd
import scipy.stats
from termcolor import colored

# importing the code from Statistical_Analysis.py
from Statistical_Analysis import Analysis

In [ ]:
# Now, we can use pandas read_excel after installing the excel importer.
# df is the DataFrame Object which I have used for simplified Analysis
df = pd.read_excel('data_deKok_roels.xlsx')
df

,Dilution Rate (1/h),Dry weight (g/L),Glucose Consumption Rate (C mol/C mol biomass),Oxygen Consumption Rate (mol O2/C mol biomass),Carbon Dioxide Production Rate (mol CO2/C mol biomass)
0,0.008,3.60,2.00,1.10,1.40
1,0.008,3.80,2.10,3.80,1.40
2,0.017,3.20,2.30,1.50,1.60
3,0.033,4.00,1.90,1.04,1.10
4,0.047,3.17,2.48,1.20,1.20
5,0.052,4.20,1.80,0.82,0.86
6,0.072,4.41,1.74,0.54,0.73
7,0.076,4.00,1.93,0.67,0.73
8,0.092,4.40,1.80,0.70,0.70
9,0.092,3.80,1.90,0.70,0.80
10,0.102,4.40,1.80,0.62,0.85
11,0.112,3.60,2.10,0.78,0.92
12,0.113,4.30,1.80,0.80,1.00
13,0.118,4.50,1.71,0.57,0.67

In [1]:
# col and row are two variables
col = df.columns
row = df.index

# df2 is the 
df2 = pd.DataFrame()

df2["D"] = df[col[0]]
df2["DW"] = df[col[1]]

df2['CH2O'] = -df[col[2]]
df2['O2'] = -df[col[3]]
df2['NH3'] = None
df2['CH1.83O0.56N0.17'] = 1.00
df2['H2O'] = None
df2['CO2'] = df[col[4]]
df2

NameError: ignored

In [ ]:
reactants = ['CH2O', 'O2', 'NH3']
products = ['CH1.83O0.56N0.17', 'H2O', 'CO2']


error_percent_orig = [6, 11.7, None, 5, None, 11.1]
analysis1 = Analysis(reactants, products, error_percent_orig, df2)
analysis1.perform_analysis(0.9)

all element involved in chemical reaction are: ['C', 'H', 'N', 'O']
reactant_i = CH2O , --> (1, 2.0, 0, 1)
reactant_i = O2 , --> (0, 0, 0, 2.0)
reactant_i = NH3 , --> (0, 3.0, 1, 0)
product_i = CH1.83O0.56N0.17 , --> (1, 1.83, 0.17, 0.56)
product_i = H2O , --> (0, 2.0, 0, 1)
product_i = CO2 , --> (1, 0, 0, 2.0)

   CH2O   O2  NH3  CH1.83O0.56N0.17  H2O  CO2
C  -1.0 -0.0 -0.0              1.00  0.0  1.0
H  -2.0 -0.0 -3.0              1.83  2.0  0.0
N  -0.0 -0.0 -1.0              0.17  0.0  0.0
O  -1.0 -2.0 -0.0              0.56  1.0  2.0

A =

[[-1.   -0.   -0.    1.    0.    1.  ]
 [-2.   -0.   -3.    1.83  2.    0.  ]
 [-0.   -0.   -1.    0.17  0.    0.  ]
 [-1.   -2.   -0.    0.56  1.    2.  ]]

i =  0
all_coeff =  [2.0, 1.1, None, 1.0, None, 1.4]
coeff not measured [2, 4]

   CH2O   O2  NH3  CH1.83O0.56N0.17  H2O  CO2
C  -1.0  0.0  0.0               1.0  0.0  1.0
H   0.0  4.0  0.0               0.2  0.0 -4.0

   CH2O   O2  CH1.83O0.56N0.17  CO2
C  -1.0  0.0               1.0  1.0
H   0.0  4.0               0.2 -4.0

A =

[[-1.   0.   1.   1. ]
 [ 0.   4.   0.2 -4. ]]

x_measured =  [[2. ]
 [1.1]
 [1. ]
 [1.4]]

We have chi-square with 2 degrees of freedom at 90.0 % confidence level =  4.605170185988092

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

h_org = 3.9072470360401614
deleting the measurement for CH2O
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for O2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

********************************************
    *************Test Failed********************
    ********************************************

deleting the measurement for CH1.83O0.56N0.17
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CO2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------


Deletion of stoichiometric coefficients of ['CH2O', 'CH1.83O0.56N0.17', 'CO2'] passes the chi-square test
Hence ['CH2O', 'CH1.83O0.56N0.17', 'CO2'] measurements can be suspected of containg GROSS ERRORS
-----------------------------

{'CH2O': 1.534906223369375,
 'O2': 3.897765508478125,
 'CH1.83O0.56N0.17': 1.6865576008039307,
 'CO2': 0.6672609737739759}

-------------------------------
i =  1
all_coeff =  [2.1, 3.8, None, 1.0, None, 1.4]
coeff not measured [2, 4]

   CH2O   O2  NH3  CH1.83O0.56N0.17  H2O  CO2
C  -1.0  0.0  0.0               1.0  0.0  1.0
H   0.0  4.0  0.0               0.2  0.0 -4.0

   CH2O   O2  CH1.83O0.56N0.17  CO2
C  -1.0  0.0               1.0  1.0
H   0.0  4.0               0.2 -4.0

A =

[[-1.   0.   1.   1. ]
 [ 0.   4.   0.2 -4. ]]

x_measured =  [[2.1]
 [3.8]
 [1. ]
 [1.4]]

We have chi-square with 2 degrees of freedom at 90.0 % confidence level =  4.605170185988092

********************************************
    *************Test Failed********************
    ********************************************

h_org = 35.065291815623524
deleting the measurement for CH2O
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

********************************************
    *************Test Failed********************
    ********************************************

deleting the measurement for O2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CH1.83O0.56N0.17
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

********************************************
    *************Test Failed********************
    ********************************************

deleting the measurement for CO2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

********************************************
    *************Test Failed********************
    ********************************************


Deletion of stoichiometric coefficients of ['O2'] passes the chi-square test
Hence ['O2'] measurements can be suspected of containg GROSS ERRORS
-----------------------------

{'CH2O': 27.059671523312318,
 'O2': 2.116394153484664,
 'CH1.83O0.56N0.17': 26.43042753382344,
 'CO2': 34.96278641919163}

-------------------------------
i =  2
all_coeff =  [2.3, 1.5, None, 1.0, None, 1.6]
coeff not measured [2, 4]

   CH2O   O2  NH3  CH1.83O0.56N0.17  H2O  CO2
C  -1.0  0.0  0.0               1.0  0.0  1.0
H   0.0  4.0  0.0               0.2  0.0 -4.0

   CH2O   O2  CH1.83O0.56N0.17  CO2
C  -1.0  0.0               1.0  1.0
H   0.0  4.0               0.2 -4.0

A =

[[-1.   0.   1.   1. ]
 [ 0.   4.   0.2 -4. ]]

x_measured =  [[2.3]
 [1.5]
 [1. ]
 [1.6]]

We have chi-square with 2 degrees of freedom at 90.0 % confidence level =  4.605170185988092

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

h_org = 2.067148107565502
deleting the measurement for CH2O
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for O2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CH1.83O0.56N0.17
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CO2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------


Deletion of stoichiometric coefficients of ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] passes the chi-square test
Hence ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] measurements can be suspected of containg GROSS ERRORS
-----------------------------

{'CH2O': 0.040097349950103015,
 'O2': 1.6953699071088024,
 'CH1.83O0.56N0.17': 0.06438325752231434,
 'CO2': 1.1882016330643268}

-------------------------------
i =  3
all_coeff =  [1.9, 1.04, None, 1.0, None, 1.1]
coeff not measured [2, 4]

   CH2O   O2  NH3  CH1.83O0.56N0.17  H2O  CO2
C  -1.0  0.0  0.0               1.0  0.0  1.0
H   0.0  4.0  0.0               0.2  0.0 -4.0

   CH2O   O2  CH1.83O0.56N0.17  CO2
C  -1.0  0.0               1.0  1.0
H   0.0  4.0               0.2 -4.0

A =

[[-1.   0.   1.   1. ]
 [ 0.   4.   0.2 -4. ]]

x_measured =  [[1.9 ]
 [1.04]
 [1.  ]
 [1.1 ]]

We have chi-square with 2 degrees of freedom at 90.0 % confidence level =  4.605170185988092

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

h_org = 1.6534077299998984
deleting the measurement for CH2O
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for O2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CH1.83O0.56N0.17
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CO2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------


Deletion of stoichiometric coefficients of ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] passes the chi-square test
Hence ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] measurements can be suspected of containg GROSS ERRORS
-----------------------------

{'CH2O': 0.003364660294610237,
 'O2': 1.3155986253309988,
 'CH1.83O0.56N0.17': 0.012789754107520986,
 'CO2': 1.1813495058706285}

-------------------------------
i =  4
all_coeff =  [2.48, 1.2, None, 1.0, None, 1.2]
coeff not measured [2, 4]

   CH2O   O2  NH3  CH1.83O0.56N0.17  H2O  CO2
C  -1.0  0.0  0.0               1.0  0.0  1.0
H   0.0  4.0  0.0               0.2  0.0 -4.0

   CH2O   O2  CH1.83O0.56N0.17  CO2
C  -1.0  0.0               1.0  1.0
H   0.0  4.0               0.2 -4.0

A =

[[-1.   0.   1.   1. ]
 [ 0.   4.   0.2 -4. ]]

x_measured =  [[2.48]
 [1.2 ]
 [1.  ]
 [1.2 ]]

We have chi-square with 2 degrees of freedom at 90.0 % confidence level =  4.605170185988092

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

h_org = 1.9959958807622737
deleting the measurement for CH2O
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for O2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CH1.83O0.56N0.17
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CO2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------


Deletion of stoichiometric coefficients of ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] passes the chi-square test
Hence ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] measurements can be suspected of containg GROSS ERRORS
-----------------------------

{'CH2O': 0.0667366957060275,
 'O2': 1.8497685901743322,
 'CH1.83O0.56N0.17': 0.10414883283179684,
 'CO2': 1.185836760267071}

-------------------------------
i =  5
all_coeff =  [1.8, 0.82, None, 1.0, None, 0.86]
coeff not measured [2, 4]

   CH2O   O2  NH3  CH1.83O0.56N0.17  H2O  CO2
C  -1.0  0.0  0.0               1.0  0.0  1.0
H   0.0  4.0  0.0               0.2  0.0 -4.0

   CH2O   O2  CH1.83O0.56N0.17  CO2
C  -1.0  0.0               1.0  1.0
H   0.0  4.0               0.2 -4.0

A =

[[-1.   0.   1.   1. ]
 [ 0.   4.   0.2 -4. ]]

x_measured =  [[1.8 ]
 [0.82]
 [1.  ]
 [0.86]]

We have chi-square with 2 degrees of freedom at 90.0 % confidence level =  4.605170185988092

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

h_org = 0.22872543109779245
deleting the measurement for CH2O
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for O2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CH1.83O0.56N0.17
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CO2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------


Deletion of stoichiometric coefficients of ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] passes the chi-square test
Hence ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] measurements can be suspected of containg GROSS ERRORS
-----------------------------

{'CH2O': 0.005457518750451696,
 'O2': 0.15466168623958965,
 'CH1.83O0.56N0.17': 0.0025414545087478336,
 'CO2': 0.20740974619921193}

-------------------------------
i =  6
all_coeff =  [1.74, 0.54, None, 1.0, None, 0.73]
coeff not measured [2, 4]

   CH2O   O2  NH3  CH1.83O0.56N0.17  H2O  CO2
C  -1.0  0.0  0.0               1.0  0.0  1.0
H   0.0  4.0  0.0               0.2  0.0 -4.0

   CH2O   O2  CH1.83O0.56N0.17  CO2
C  -1.0  0.0               1.0  1.0
H   0.0  4.0               0.2 -4.0

A =

[[-1.   0.   1.   1. ]
 [ 0.   4.   0.2 -4. ]]

x_measured =  [[1.74]
 [0.54]
 [1.  ]
 [0.73]]

We have chi-square with 2 degrees of freedom at 90.0 % confidence level =  4.605170185988092

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

h_org = 2.422373513931512
deleting the measurement for CH2O
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for O2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CH1.83O0.56N0.17
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CO2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------


Deletion of stoichiometric coefficients of ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] passes the chi-square test
Hence ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] measurements can be suspected of containg GROSS ERRORS
-----------------------------

{'CH2O': 1.8553888533898506,
 'O2': 0.005008709921160962,
 'CH1.83O0.56N0.17': 1.7285980570244843,
 'CO2': 1.2749809568844266}

-------------------------------
i =  7
all_coeff =  [1.93, 0.67, None, 1.0, None, 0.73]
coeff not measured [2, 4]

   CH2O   O2  NH3  CH1.83O0.56N0.17  H2O  CO2
C  -1.0  0.0  0.0               1.0  0.0  1.0
H   0.0  4.0  0.0               0.2  0.0 -4.0

   CH2O   O2  CH1.83O0.56N0.17  CO2
C  -1.0  0.0               1.0  1.0
H   0.0  4.0               0.2 -4.0

A =

[[-1.   0.   1.   1. ]
 [ 0.   4.   0.2 -4. ]]

x_measured =  [[1.93]
 [0.67]
 [1.  ]
 [0.73]]

We have chi-square with 2 degrees of freedom at 90.0 % confidence level =  4.605170185988092

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

h_org = 2.19652227627225
deleting the measurement for CH2O
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for O2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CH1.83O0.56N0.17
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CO2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------


Deletion of stoichiometric coefficients of ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] passes the chi-square test
Hence ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] measurements can be suspected of containg GROSS ERRORS
-----------------------------

{'CH2O': 0.007863426127790195,
 'O2': 1.779715619152229,
 'CH1.83O0.56N0.17': 5.879396961878544e-31,
 'CO2': 1.976613914337342}

-------------------------------
i =  8
all_coeff =  [1.8, 0.7, None, 1.0, None, 0.7]
coeff not measured [2, 4]

   CH2O   O2  NH3  CH1.83O0.56N0.17  H2O  CO2
C  -1.0  0.0  0.0               1.0  0.0  1.0
H   0.0  4.0  0.0               0.2  0.0 -4.0

   CH2O   O2  CH1.83O0.56N0.17  CO2
C  -1.0  0.0               1.0  1.0
H   0.0  4.0               0.2 -4.0

A =

[[-1.   0.   1.   1. ]
 [ 0.   4.   0.2 -4. ]]

x_measured =  [[1.8]
 [0.7]
 [1. ]
 [0.7]]

We have chi-square with 2 degrees of freedom at 90.0 % confidence level =  4.605170185988092

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

h_org = 0.5340224530709629
deleting the measurement for CH2O
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for O2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CH1.83O0.56N0.17
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CO2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------


Deletion of stoichiometric coefficients of ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] passes the chi-square test
Hence ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] measurements can be suspected of containg GROSS ERRORS
-----------------------------

{'CH2O': 0.1960607474619936,
 'O2': 0.49501789242172256,
 'CH1.83O0.56N0.17': 0.22586624366436608,
 'CO2': 0.118327175587116}

-------------------------------
i =  9
all_coeff =  [1.9, 0.7, None, 1.0, None, 0.8]
coeff not measured [2, 4]

   CH2O   O2  NH3  CH1.83O0.56N0.17  H2O  CO2
C  -1.0  0.0  0.0               1.0  0.0  1.0
H   0.0  4.0  0.0               0.2  0.0 -4.0

   CH2O   O2  CH1.83O0.56N0.17  CO2
C  -1.0  0.0               1.0  1.0
H   0.0  4.0               0.2 -4.0

A =

[[-1.   0.   1.   1. ]
 [ 0.   4.   0.2 -4. ]]

x_measured =  [[1.9]
 [0.7]
 [1. ]
 [0.8]]

We have chi-square with 2 degrees of freedom at 90.0 % confidence level =  4.605170185988092

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

h_org = 1.0032823882829904
deleting the measurement for CH2O
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for O2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CH1.83O0.56N0.17
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CO2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------


Deletion of stoichiometric coefficients of ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] passes the chi-square test
Hence ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] measurements can be suspected of containg GROSS ERRORS
-----------------------------

{'CH2O': 0.17124108690142748,
 'O2': 0.4276896547004793,
 'CH1.83O0.56N0.17': 0.1312055563045617,
 'CO2': 1.0017871883440046}

-------------------------------
i =  10
all_coeff =  [1.8, 0.62, None, 1.0, None, 0.85]
coeff not measured [2, 4]

   CH2O   O2  NH3  CH1.83O0.56N0.17  H2O  CO2
C  -1.0  0.0  0.0               1.0  0.0  1.0
H   0.0  4.0  0.0               0.2  0.0 -4.0

   CH2O   O2  CH1.83O0.56N0.17  CO2
C  -1.0  0.0               1.0  1.0
H   0.0  4.0               0.2 -4.0

A =

[[-1.   0.   1.   1. ]
 [ 0.   4.   0.2 -4. ]]

x_measured =  [[1.8 ]
 [0.62]
 [1.  ]
 [0.85]]

We have chi-square with 2 degrees of freedom at 90.0 % confidence level =  4.605170185988092

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

h_org = 2.5009588635847044
deleting the measurement for CH2O
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for O2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CH1.83O0.56N0.17
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CO2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------


Deletion of stoichiometric coefficients of ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] passes the chi-square test
Hence ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] measurements can be suspected of containg GROSS ERRORS
-----------------------------

{'CH2O': 2.286484657642076,
 'O2': 0.10838499955941469,
 'CH1.83O0.56N0.17': 2.2048969619563,
 'CO2': 0.8586394184712628}

-------------------------------
i =  11
all_coeff =  [2.1, 0.78, None, 1.0, None, 0.92]
coeff not measured [2, 4]

   CH2O   O2  NH3  CH1.83O0.56N0.17  H2O  CO2
C  -1.0  0.0  0.0               1.0  0.0  1.0
H   0.0  4.0  0.0               0.2  0.0 -4.0

   CH2O   O2  CH1.83O0.56N0.17  CO2
C  -1.0  0.0               1.0  1.0
H   0.0  4.0               0.2 -4.0

A =

[[-1.   0.   1.   1. ]
 [ 0.   4.   0.2 -4. ]]

x_measured =  [[2.1 ]
 [0.78]
 [1.  ]
 [0.92]]

We have chi-square with 2 degrees of freedom at 90.0 % confidence level =  4.605170185988092

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

h_org = 2.705672705028973
deleting the measurement for CH2O
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for O2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CH1.83O0.56N0.17
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CO2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------


Deletion of stoichiometric coefficients of ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] passes the chi-square test
Hence ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] measurements can be suspected of containg GROSS ERRORS
-----------------------------

{'CH2O': 0.43169765047754316,
 'O2': 1.1248244648932304,
 'CH1.83O0.56N0.17': 0.3302711947298695,
 'CO2': 2.703941986891289}

-------------------------------
i =  12
all_coeff =  [1.8, 0.8, None, 1.0, None, 1.0]
coeff not measured [2, 4]

   CH2O   O2  NH3  CH1.83O0.56N0.17  H2O  CO2
C  -1.0  0.0  0.0               1.0  0.0  1.0
H   0.0  4.0  0.0               0.2  0.0 -4.0

   CH2O   O2  CH1.83O0.56N0.17  CO2
C  -1.0  0.0               1.0  1.0
H   0.0  4.0               0.2 -4.0

A =

[[-1.   0.   1.   1. ]
 [ 0.   4.   0.2 -4. ]]

x_measured =  [[1.8]
 [0.8]
 [1. ]
 [1. ]]

We have chi-square with 2 degrees of freedom at 90.0 % confidence level =  4.605170185988092

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

h_org = 1.726982594896318
deleting the measurement for CH2O
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for O2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CH1.83O0.56N0.17
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CO2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------


Deletion of stoichiometric coefficients of ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] passes the chi-square test
Hence ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] measurements can be suspected of containg GROSS ERRORS
-----------------------------

{'CH2O': 1.0669468864355955,
 'O2': 1.5102888427411734,
 'CH1.83O0.56N0.17': 1.1441840643540955,
 'CO2': 0.10784596662555597}

-------------------------------
i =  13
all_coeff =  [1.71, 0.57, None, 1.0, None, 0.67]
coeff not measured [2, 4]

   CH2O   O2  NH3  CH1.83O0.56N0.17  H2O  CO2
C  -1.0  0.0  0.0               1.0  0.0  1.0
H   0.0  4.0  0.0               0.2  0.0 -4.0

   CH2O   O2  CH1.83O0.56N0.17  CO2
C  -1.0  0.0               1.0  1.0
H   0.0  4.0               0.2 -4.0

A =

[[-1.   0.   1.   1. ]
 [ 0.   4.   0.2 -4. ]]

x_measured =  [[1.71]
 [0.57]
 [1.  ]
 [0.67]]

We have chi-square with 2 degrees of freedom at 90.0 % confidence level =  4.605170185988092

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

h_org = 0.5381803569831478
deleting the measurement for CH2O
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for O2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CH1.83O0.56N0.17
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------

deleting the measurement for CO2
performing row operations and delting corresponding row and column


We have chi-square with 1 degrees of freedom at 90.0 % confidence level =  2.705543454095404

--------------------------------------------
    --------------Test Passed-------------------
    --------------------------------------------


Deletion of stoichiometric coefficients of ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] passes the chi-square test
Hence ['CH2O', 'O2', 'CH1.83O0.56N0.17', 'CO2'] measurements can be suspected of containg GROSS ERRORS
-----------------------------

{'CH2O': 0.2503830108917622,
 'O2': 0.08621778108205043,
 'CH1.83O0.56N0.17': 0.21794062163962588,
 'CO2': 0.4568382055212549}

-------------------------------

,D,DW,h (no deletion),h after deleting CH2O,h after deleting O2,h after deleting CH1.83O0.56N0.17,h after deleting CO2
0,0.008,3.60,3.91,1.53,3.90,1.69,0.67
1,0.008,3.80,35.07,27.06,2.12,26.43,34.96
2,0.017,3.20,2.07,0.04,1.70,0.06,1.19
3,0.033,4.00,1.65,0.00,1.32,0.01,1.18
4,0.047,3.17,2.00,0.07,1.85,0.10,1.19
5,0.052,4.20,0.23,0.01,0.15,0.00,0.21
6,0.072,4.41,2.42,1.86,0.01,1.73,1.27
7,0.076,4.00,2.20,0.01,1.78,0.00,1.98
8,0.092,4.40,0.53,0.20,0.50,0.23,0.12
9,0.092,3.80,1.00,0.17,0.43,0.13,1.00
10,0.102,4.40,2.50,2.29,0.11,2.20,0.86
11,0.112,3.60,2.71,0.43,1.12,0.33,2.70
12,0.113,4.30,1.73,1.07,1.51,1.14,0.11
13,0.118,4.50,0.54,0.25,0.09,0.22,0.46

In [ ]:
df3 = df2.copy()
df3['RQ'] = df3['CO2'] / (-df3['O2'])
df3

        D    DW  CH2O    O2   NH3  CH1.83O0.56N0.17   H2O   CO2        RQ
0   0.008  3.60 -2.00 -1.10  None               1.0  None  1.40  1.272727
1   0.008  3.80 -2.10 -3.80  None               1.0  None  1.40  0.368421
2   0.017  3.20 -2.30 -1.50  None               1.0  None  1.60  1.066667
3   0.033  4.00 -1.90 -1.04  None               1.0  None  1.10  1.057692
4   0.047  3.17 -2.48 -1.20  None               1.0  None  1.20  1.000000
5   0.052  4.20 -1.80 -0.82  None               1.0  None  0.86  1.048780
6   0.072  4.41 -1.74 -0.54  None               1.0  None  0.73  1.351852
7   0.076  4.00 -1.93 -0.67  None               1.0  None  0.73  1.089552
8   0.092  4.40 -1.80 -0.70  None               1.0  None  0.70  1.000000
9   0.092  3.80 -1.90 -0.70  None               1.0  None  0.80  1.142857
10  0.102  4.40 -1.80 -0.62  None               1.0  None  0.85  1.370968
11  0.112  3.60 -2.10 -0.78  None               1.0  None  0.92  1.179487
12  0.113  4.30 -1.80 -0.80  None               1.0  None  1.00  1.250000
13  0.118  4.50 -1.71 -0.57  None               1.0  None  0.67  1.175439